robot:

    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100

    right_joint_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: joint_right_wheel
        pid: {p: 10.0, i: 10.0, d: 0.01}

    left_joint_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: joint_left_wheel
        pid: {p: 10.0, i: 10.0, d: 0.01}
           
        
    alo_joint_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: joint_alo_wheel
        pid: {p: 10.0, i: 10.0, d: 0.01}    
    
    
    third_joint_velocity_controller:
        type: effort_controllers/JointVelocityController
        joint: joint_third_wheel
        pid: {p: 10.0, i: 10.0, d: 0.01}
